### PR TITLE
slice-into-datum

### PR DESCRIPTION
**Pull request by jcrist1**
I created a PR to add `IntoDatum` for slices of `T: IntoDatum + Copy`, e.g. slices of floats. The implementation copy pastes the code from the `IntoDatum` for `Vec<T: IntoDatum>`, so maybe that could be DRY'd out a bit, but I feel like any solution would introduce unecessary abstraction. I also implemented a simple test to check that it works at advertised, and it looks like it does.  I discussed with @Hoverbear in Discord, about incorporating this, and she said :
>[Hoverbear](https://discord.com/channels/561648697805504526/749454413407584258/893857619150770237)
> — 
>Today at 15:51
>Admittedly I thought we did!
>It does look like we do not: https://github.com/zombodb/pgx/blob/8a860a57d874865c7f305702548a4e0b0655a450/pgx/src/datum/into.rs#L20
>I think we can add this though

Surprisingly I wasn't able to get the test to run on the develop branch, bec~e~ause of a failed linking step. 
```
[I] pgx ) cargo pgx test  pg13                                                                                                                                                                                                                                           (base)
"cargo" "test" "--all" "--features" " pg13 pg_test" "--no-default-features"
   Compiling pgx-tests v0.2.0-beta.1 (/Users/jan/workspace/rust/pgx/pgx-tests)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-Wl,-exported_symbols_list,/var/folders/_9/1yvfs1c54lv0z3njhdhwxx3h0000gn/T/rustckc06rQ/list" "-m64" "-arch" "x86_64" ...{LOTS OF STUFF}... "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-nodefaultlibs"
  = note: Undefined symbols for architecture x86_64:
            "_errcode", referenced from:
                _pgx_ereport in libpgx_pg_sys-30ef60a99f3e545f.rlib(pgx-cshim.o)
               (maybe you meant: pgx_pg_sys::pg13::GUC_check_errcode::_$u7b$$u7b$closure$u7d$$u7d$::hcb20bf19a476a1b8, pgx_pg_sys::pg13::GUC_check_errcode::h656e8fec8d38545c )
            "_errmsg", referenced from:
```
I checked ~out~ out the 1.22 release and copied my code over ~same code~, and the test I added passes.
Edit: me write gud

### CODE REVIEW

**Comment by Hoverbear** [comment]
Oh! I think you found a bug! Thanks! I'll take a look at this. :)

**Comment by Hoverbear** [comment]
Any chance you can tell me your OS and Rust version?

**Comment by jcrist1** [comment]
@Hoverbear 
Mac OS Big Sur 11.5.2
```bash
> rustc --version
rustc 1.54.0 (a178d0322 2021-07-26)
> cargo --version
cargo 1.54.0 (5ae8d74b3 2021-06-22)
> cargo pgx --version
cargo-pgx 0.1.22
```

**Comment by jcrist1** [comment]
for good measure:
```
> cc --version
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by Hoverbear** [comment]
I'm able to experience this issue *only* while running from the `pgx` root dir and running `cargo test --features "pg13 pg_test"` and it occurs during the `pgx-tests` link phase. I suspect this is related to the `.cargo/config` used in that directory.

**Comment by eeeebbbbrrrr** [comment]
> Investigating this shmem failure... Seems unrelated.

Per discord, I fixed it in #245. So once we merge all this stuff things should work

**Pull request merged**
