### PR TITLE
run bindgen on parser.h

### PR DESCRIPTION
**Pull request by ethanpailes**
This patch provides access to to the routines defined in
parser.h via bindgen. I'm interested in the parser.h header
because I want to be able to invoke raw_parser to get a
parse tree that I can poke at.

### CODE REVIEW

**Comment by eeeebbbbrrrr** [comment]
Please retarget this to the “develop” branch.

**Comment by ethanpailes** [comment]
@eeeebbbbrrrr you might want to change the default branch so that the PRs that github automatically generates go the right place.

**Comment by eeeebbbbrrrr** [comment]
Doesn't that also change the branch that's shown on the landing page of the repo?  I want that to always be master

**Comment by ethanpailes** [comment]
I would assume so.

**Pull request closed without merging**
